
import React, { useState, useRef, useEffect } from 'react';
import { analyzeData } from '../services/geminiService';
import { useToolContext } from '../contexts/ToolContext';
import Button from '../components/Button';
import { TextArea } from '../components/Input';
import { BarChart, FileText, PieChart, Upload } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

const DataAnalyzer: React.FC = () => {
  const { dataState, setDataState } = useToolContext();
  const [dataInput, setDataInput] = useState(dataState.dataInput);
  const [query, setQuery] = useState(dataState.query);
  const [result, setResult] = useState(dataState.result);
  const [isLoading, setIsLoading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setDataState({ dataInput, query, result });
  }, [dataInput, query, result, setDataState]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
        const text = e.target?.result as string;
        setDataInput(text);
    };
    reader.readAsText(file);
  };

  const handleAnalyze = async () => {
    if (!dataInput.trim() || !query.trim()) return;
    setIsLoading(true);
    setResult('');

    try {
      const response = await analyzeData(dataInput, query);
      setResult(response);
    } catch (error) {
      setResult("Error analyzing data. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-fade-in h-full flex flex-col">
       <div className="flex items-center gap-3 mb-4">
         <div className="p-3 bg-blue-600/20 rounded-lg text-blue-400">
           <BarChart size={24} />
         </div>
         <div>
           <h2 className="text-2xl font-bold text-white">Data Lab Pro</h2>
           <p className="text-gray-400 text-sm">Extract insights from CSV, JSON, or text files instantly.</p>
         </div>
       </div>

       <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-1">
          <div className="space-y-4 flex flex-col">
            <div className="bg-gray-900 p-6 rounded-xl border border-gray-800 flex-1 flex flex-col gap-4">
               
               <div className="flex justify-end">
                   <button 
                     onClick={() => fileInputRef.current?.click()}
                     className="text-xs text-blue-400 hover:text-white flex items-center gap-1 font-bold bg-blue-900/20 px-3 py-1.5 rounded-lg border border-blue-500/20"
                   >
                       <Upload size={12} /> Upload File (CSV/JSON/TXT)
                   </button>
                   <input type="file" ref={fileInputRef} className="hidden" accept=".csv,.json,.txt" onChange={handleFileUpload} />
               </div>

               <TextArea 
                 label="Data Input" 
                 placeholder="Paste your CSV, JSON, or unstructured text here..." 
                 value={dataInput}
                 onChange={(e) => setDataInput(e.target.value)}
                 className="h-48 font-mono text-xs bg-gray-950"
               />
               <TextArea 
                 label="Analysis Question" 
                 placeholder="E.g., What are the main trends? Summarize the sales figures. What is the sentiment?" 
                 value={query}
                 onChange={(e) => setQuery(e.target.value)}
                 className="h-24"
               />
               <Button onClick={handleAnalyze} disabled={isLoading || !dataInput || !query} className="!bg-blue-600 hover:!bg-blue-500" icon={<PieChart size={18} />}>
                 {isLoading ? 'Analyzing...' : 'Analyze Data'}
               </Button>
            </div>
          </div>

          <div className="bg-gray-900 rounded-xl border border-gray-800 flex flex-col overflow-hidden">
             <div className="bg-gray-800 px-4 py-3 border-b border-gray-700 flex justify-between items-center">
               <span className="font-semibold text-gray-200">Analysis Report</span>
               <span className="text-xs text-gray-500">ZamanX AI</span>
             </div>
             <div className="flex-1 p-6 overflow-y-auto bg-gray-950 text-gray-300">
                {result ? (
                  <div className="prose prose-invert max-w-none text-sm">
                    <ReactMarkdown>{result}</ReactMarkdown>
                    <div className="mt-8 pt-4 border-t border-gray-800 text-center text-xs text-gray-600">
                        Generated by ZamanX AI
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full text-gray-600">
                    <FileText size={48} className="mb-4 opacity-20" />
                    <p>Waiting for data...</p>
                  </div>
                )}
             </div>
          </div>
       </div>
    </div>
  );
};

export default DataAnalyzer;
