
import React, { useState, useEffect } from 'react';
import { solveMath } from '../services/geminiService';
import { useToolContext } from '../contexts/ToolContext';
import Button from '../components/Button';
import { TextArea } from '../components/Input';
import { Calculator, Sigma, BrainCircuit } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

const MathSolver: React.FC = () => {
  const { mathState, setMathState } = useToolContext();
  const [problem, setProblem] = useState(mathState.problem);
  const [solution, setSolution] = useState(mathState.solution);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setMathState({ problem, solution });
  }, [problem, solution, setMathState]);

  const handleSolve = async () => {
    if (!problem.trim()) return;
    setIsLoading(true);
    setSolution('');
    try {
      const result = await solveMath(problem);
      setSolution(result);
    } catch (error) {
      setSolution("Error solving problem. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fade-in">
      <div className="text-center space-y-3">
        <h2 className="text-3xl font-bold text-white flex items-center justify-center gap-3">
          <div className="p-2 bg-indigo-500/20 rounded-lg">
             <Calculator className="text-indigo-400" size={32} />
          </div>
          Math Genius
        </h2>
        <p className="text-gray-400">Solve algebra, calculus, geometry, and logic problems with step-by-step explanations.</p>
      </div>

      <div className="grid gap-6">
        <div className="bg-slate-900 rounded-2xl border border-slate-800 p-6 shadow-xl relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-10 pointer-events-none">
             <Sigma size={120} />
          </div>
          <TextArea
            label="Enter Math Problem"
            placeholder="E.g., Solve for x: 2x^2 + 5x - 3 = 0, or 'Calculate the derivative of sin(x)/x'"
            rows={3}
            value={problem}
            onChange={(e) => setProblem(e.target.value)}
            className="font-mono text-lg"
          />
          <div className="mt-4 flex justify-end">
            <Button 
              onClick={handleSolve} 
              disabled={isLoading || !problem.trim()}
              className="px-8 !bg-indigo-600 hover:!bg-indigo-500"
              icon={<BrainCircuit size={18} />}
            >
              {isLoading ? 'Solving...' : 'Solve Problem'}
            </Button>
          </div>
        </div>

        {solution && (
          <div className="bg-slate-900 rounded-2xl border border-slate-800 overflow-hidden shadow-2xl animate-fade-in">
            <div className="bg-indigo-900/20 px-6 py-3 border-b border-slate-700 flex items-center justify-between">
               <span className="font-semibold text-indigo-200">Solution</span>
               <span className="text-xs bg-indigo-500/20 text-indigo-300 px-2 py-1 rounded">Step-by-Step</span>
            </div>
            <div className="p-8 prose prose-invert prose-indigo max-w-none">
              <ReactMarkdown>{solution}</ReactMarkdown>
            </div>
            <div className="bg-slate-950 p-3 text-center text-xs text-gray-500">
               Generated by ZamanX AI • Verify important calculations
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default MathSolver;
